name: f_json_editor
description: "Json Editor and Json Viewer"
repository: 'https://github.com/ysfgrl/f_json_editor.git'
homepage: 'https://github.com/ysfgrl/f_json_editor.git'
version: 1.0.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:  ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: